POST http://localhost:4000/app/signupofficials
Content-Type: application/json

{
    "firstName":"Francis",
    "lastName":"Abucejo",
    "address":"dito lang",
    "email":"email@gmail.com",
    "contactNo":"09 999 9999",
    "age":"60"
}